# Generated by Django 3.0.1 on 2020-01-06 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_faculty'),
    ]

    operations = [
        migrations.CreateModel(
            name='facultysignup',
            fields=[
                ('factid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('dob', models.DateField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('qualification', models.CharField(max_length=20)),
                ('mobile', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=10)),
                ('assignedbatch', models.CharField(max_length=20)),
            ],
        ),
    ]
