# Generated by Django 3.0.1 on 2020-01-06 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facultysignup',
            old_name='assignedbatch',
            new_name='assbatch',
        ),
    ]
