# Generated by Django 3.0.1 on 2020-01-07 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_auto_20200106_1843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='admnno',
            new_name='admno',
        ),
    ]
