# Generated by Django 3.0.1 on 2020-01-07 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_auto_20200107_1010'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentattend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=10)),
                ('stdid', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=30)),
                ('hour1status', models.CharField(max_length=30)),
                ('hour2status', models.CharField(max_length=30)),
                ('hour3status', models.CharField(max_length=30)),
                ('hour4status', models.CharField(max_length=30)),
            ],
        ),
    ]
