# Generated by Django 3.0.1 on 2020-01-09 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0011_studentmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='facultyattendence',
            fields=[
                ('date', models.DateField(max_length=10)),
                ('factid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('hour1status', models.CharField(max_length=30)),
                ('hour2status', models.CharField(max_length=30)),
                ('hour3status', models.CharField(max_length=30)),
                ('hour4status', models.CharField(max_length=30)),
            ],
        ),
    ]
